Feature/notaxon
StructuralEquationModels/Taxonomy.jl pull request #101
Opened 2023-06-07 15:01 UTC by aaronpeikert

2023-06-13 14:07 UTC, aaronpeikert commented on src/taxons/no_taxon.jl
> +NoTaxonYet requires a timestamp 'accessdate' to further specify at what point there were no possibility to code the respective model.
```suggestion
NoTaxonYet requires a timestamp 'accessdate' to further specify at what point there was no possibility to code the respective model.
```

2023-06-13 14:07 UTC, aaronpeikert commented on src/taxons/no_taxon.jl
> +NoTaxonYet gives you the option to name the 'modeltype', you were not able to code, to spare your future self the work of going everything through.
```suggestion
NoTaxonYet gives you the option to name the 'modeltype', you were not able to code, to spare your future self the work of going through everything.
```

2023-06-13 15:11 UTC, valentinkm requested changes

2023-06-13 15:11 UTC, valentinkm commented on docs/src/tutorials/missing.md
>  This is to encourage you to think twice, however, after having thought twice about it, you may silence every warning with explicitly suppliyng "empty" instances (except ID, really nothing should hind
```suggestion
This is to encourage you to think twice. However, after having thought twice about it, you may silence every warning with explicitly suppliyng "empty" instances (except ID, really nothing should hinder you to supply a random id).
```

2023-06-14 06:32 UTC, LeonieHagitte commented on src/abstracttypes.jl
>  AbstractPathmodel is the supertype of all pathmodels.
"""
 `AbstractPathmodel` is the supertype of all pathmodels.

2023-06-14 06:34 UTC, LeonieHagitte commented on src/abstracttypes.jl
>  AbstractPathmodel is the supertype of all pathmodels.
"""
 `AbstractPathmodel` is the supertype of all pathmodels.

2023-06-14 06:35 UTC, LeonieHagitte approved these changes

2023-06-14 14:30 UTC, merged